options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: 'E2_HIGHCPU_8' # Choose a suitable machine type if builds are large

steps:
  # Step 1: Download Go dependencies and cache them
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/cache
        export GOCACHE=/workspace/cache
        go mod download

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east1-docker.pkg.dev/pocketbase-deployment/pocketbase-repo/pocketbase:latest',
        '.',
      ]

  # Step 3: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-east1-docker.pkg.dev/pocketbase-deployment/pocketbase-repo/pocketbase:latest',
      ]

  # Step 4: Deploy the container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'pocketbase-service',
        '--image',
        'us-east1-docker.pkg.dev/pocketbase-deployment/pocketbase-repo/pocketbase:latest',
        '--region',
        'us-east1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--project',
        'pocketbase-deployment',
      ]

# Cache declaration
images:
  - 'us-east1-docker.pkg.dev/pocketbase-deployment/pocketbase-repo/pocketbase:latest'

# Declare volume caching for dependencies
volumes:
  - name: 'gocache'
    path: '/workspace/cache'
